### PR TITLE
Update coffee file and OS

### PR DESCRIPTION
**Pull request by acostach**

### CODE REVIEW

**Comment by dtischler** [comment]
Hmmm, why did this one fail @acostach?  This should have been the one to set it live in balenaCloud, similar to how it appears in the drop-down menu in Staging, correct?

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by dtischler** [comment]
Ha, looks like this one requires you to manually review as well @acostach.  :-)

**Comment by dtischler** [comment]
Wait a sec @acostach ... even if you do Review it, this is out-of-date.  Do we have to re-submit it, or, is the "Update branch" button safe to click?

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@dtischler if there aren't any major conflicts a rebase from the ci should work

**Comment by dtischler** [comment]
Aha, thanks @acostach, looks like that worked, and then just needs your Review.

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Pull request merged**
