### PR TITLE
Update LEC to SMARC in bsp-layer

### PR DESCRIPTION
**Pull request by dtischler**
recipes-bsp: Update lec occurrences

Changelog-entry: recipes-bsp: Update lec occurrences
Signed-off-by: David Tischler <david@balena.io>

### CODE REVIEW

**Comment by dtischler** [comment]
Hmmm, I added a second commit, with proper commit message, but it looks like it's still being blocked by the first commit, I think?

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by dtischler** [comment]
Looks like Jenkins passed and checks are complete, but I guess it still needs a review from you @acostach, since Merging is blocked?

**Review by acostach — APPROVED** [review]
LGTM

**Pull request merged**
